name: CICD Pipeline

on:
   push:

jobs:
   code:
      uses: ./.github/workflows/code.yml  # workflow_call
   build:
      needs: code
      uses: ./.github/wprkflows/Build.yml
   test:
      needs: build
      uses: ./.github/workflows/test.yml
   deploy: 
      needs: test
      uses: ./.github/workflow/Deploy.yml
