name: Deploy

on:
   workflow_call:

jobs:
   build:
         runs-on: self-hosted
         steps:
            - name: clone the code
              uses: actions/checkout@v7

            - name: Deploy via ngnix
              run: sudo cp Index.html /var/www/html/Index.html
            - name: Deploy the code
              run: echo "Deploy the code to AWS EC2 instance"
